### ISSUE TITLE
运行python3.6 client.py遇错

### ISSUE THREAD

**Issue by luckypoem** [lyncir/s5proxy#4]
hi。

yudeMacBook-Air:s5proxy-by-lyncir brite$ python3.6 client.py
2018-06-04 13:31:34 DEBUG    Using selector: KqueueSelector
2018-06-04 13:31:34 INFO     start client at 127.0.0.1:1098
future: <Task finished coro=<Server.connect() done, defined at client.py:68> exception=TypeError('encoding without a string argument',)>
Traceback (most recent call last):
  File "client.py", line 83, in connect
    pack('!i%ssH' % len(hostname), len(hostname), bytes(hostname, encoding='utf-8'), port))
TypeError: encoding without a string argument
2018-06-04 13:27:39 ERROR    Task exception was never retrieved
future: <Task finished coro=<Server.connect() done, defined at client.py:68> exception=TypeError('encoding without a string argument',)>
Traceback (most recent call last):
  File "client.py", line 83, in connect
    pack('!i%ssH' % len(hostname), len(hostname), bytes(hostname, encoding='utf-8'), port))
TypeError: encoding without a string argument

怎么解决？

**Comment by lyncir** [comment]
我修复下 最近一次更新有问题 bytes(hostname, encoding='utf-8')

**Comment by lyncir** [comment]
fixed by [fb5e6c9](https://github.com/lyncir/s5proxy/commit/fb5e6c9ff66fd660f3eaad68bed939504f979056)

**Comment by luckypoem** [comment]
现在可用来翻#墙了。非常感谢！
