### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by wOo00w** [lyncir/s5proxy#6]
作者你好，我启动以后浏览器使用正常 但是curl使用会报错：
MainThread 2019-10-22 17:08:16 ERROR    Task exception was never retrieved
future: <Task finished coro=<Server.connect() done, defined at client.py:73> exception=error("argument for 's' must be a bytes object",)>
Traceback (most recent call last):
  File "client.py", line 96, in connect
    pack('!i%ssH' % len(hostname), len(hostname), hostname, port))
struct.error: argument for 's' must be a bytes object

麻烦有机会看下

**Comment by lyncir** [comment]
fixed
